"""
Unit tests for perception/src/object_detect.py (Phone & Paper Chit Detection).

Covers:
- test_object_detector_init
- test_detect_phones_empty_frame
- test_detect_chits_no_tracks
- test_detect_chits_synthetic_slip_near_wrist
- test_detect_chits_ignores_distant_slip
- test_detect_chits_ignores_non_rectangular_contour
- test_process_frame_payload_conforms_to_shared_schema
- test_process_frame_bbox_format_is_xywh
- test_process_frame_no_student_id_or_seat_zone
- test_risk_score_and_category
- test_debounce_cooldown
- test_draw_detections
"""

import json
import os
import sys
import tempfile
from unittest.mock import MagicMock, patch

import cv2
import jsonschema
import numpy as np
import pytest
import torch

# Ensure perception/src is on python path
PERCEPTION_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
REPO_DIR = os.path.abspath(os.path.join(PERCEPTION_DIR, ".."))
sys.path.insert(0, PERCEPTION_DIR)

from src.object_detect import ObjectDetectionConfig, ObjectDetector

SCHEMA_PATH = os.path.join(REPO_DIR, "shared", "schema_behavior_event.json")


def load_behavior_schema() -> dict:
    with open(SCHEMA_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


class TestObjectDetector:

    @pytest.fixture
    def detector(self):
        config = ObjectDetectionConfig(
            phone_conf_threshold=0.30,
            debounce_frames=5,
        )
        return ObjectDetector(config=config)

    def test_object_detector_init(self, detector):
        """Verify detector initializes with appropriate compute device."""
        assert detector.device in ("mps", "cuda", "cpu")
        assert detector.model is not None
        assert detector.config.phone_coco_class_id == 67

    def test_detect_phones_empty_frame(self, detector):
        """Empty frame should return 0 phone detections."""
        blank_frame = np.zeros((480, 640, 3), dtype=np.uint8)
        dets = detector.detect_phones(blank_frame)
        assert isinstance(dets, list)
        assert len(dets) == 0

    def test_detect_chits_no_tracks(self, detector):
        """No tracked keypoints should return 0 chit detections."""
        frame = np.zeros((480, 640, 3), dtype=np.uint8)
        dets = detector.detect_chits(frame, tracks=None)
        assert len(dets) == 0
        dets_empty = detector.detect_chits(frame, tracks=[])
        assert len(dets_empty) == 0

    def test_detect_chits_synthetic_slip_near_wrist(self, detector):
        """A white rectangular slip placed near a wrist keypoint must trigger chit detection."""
        # Create dark frame (desk background)
        frame = np.zeros((480, 640, 3), dtype=np.uint8) + 40

        # Draw bright white rectangular slip at (200, 200) of size 40x25 px
        cv2.rectangle(frame, (200, 200), (240, 225), (245, 245, 245), -1)

        # Mock track with right_wrist at (210, 210) — directly adjacent to slip
        mock_tracks = [
            {
                "track_id": 1,
                "keypoints": [
                    {"name": "right_wrist", "x": 210.0, "y": 210.0, "confidence": 0.85},
                    {"name": "left_wrist", "x": 500.0, "y": 400.0, "confidence": 0.85},
                ],
            }
        ]

        dets = detector.detect_chits(frame, tracks=mock_tracks)
        assert len(dets) >= 1
        chit = dets[0]
        assert chit["confidence"] >= 0.45
        assert "metrics" in chit
        assert chit["metrics"]["solidity"] >= 0.65
        assert chit["metrics"]["dist_to_wrist_px"] <= 45.0

    def test_detect_chits_ignores_distant_slip(self, detector):
        """A bright slip far away from any wrist (> 45px) must NOT trigger chit detection."""
        frame = np.zeros((480, 640, 3), dtype=np.uint8) + 40
        # White slip at (100, 100)
        cv2.rectangle(frame, (100, 100), (140, 125), (255, 255, 255), -1)

        # Wrist far away at (400, 400)
        mock_tracks = [
            {
                "track_id": 1,
                "keypoints": [
                    {"name": "right_wrist", "x": 400.0, "y": 400.0, "confidence": 0.90},
                ],
            }
        ]

        dets = detector.detect_chits(frame, tracks=mock_tracks)
        assert len(dets) == 0

    def test_process_frame_payload_conforms_to_shared_schema(self, detector):
        """Events generated by process_frame must strictly validate against shared schema."""
        schema = load_behavior_schema()

        # Synthetic frame with slip near wrist
        frame = np.zeros((480, 640, 3), dtype=np.uint8) + 30
        cv2.rectangle(frame, (200, 200), (235, 220), (250, 250, 250), -1)
        mock_tracks = [
            {
                "track_id": 1,
                "keypoints": [
                    {"name": "left_wrist", "x": 205.0, "y": 205.0, "confidence": 0.90},
                ],
            }
        ]

        events = detector.process_frame(
            frame=frame,
            frame_number=10,
            tracks=mock_tracks,
            test_id="test_schema_check",
        )

        assert len(events) >= 1
        for ev in events:
            jsonschema.validate(instance=ev, schema=schema)
            assert ev["test_id"] == "test_schema_check"
            assert ev["frame_number"] == 10
            assert ev["event_type"] in ("phone_detected", "chit_detected")
            assert ev["risk_category"] in ("low", "high")
            assert 0.0 <= ev["risk_score"] <= 100.0
            assert len(ev["bounding_box"]) == 4

    def test_process_frame_bbox_format_is_xywh(self, detector):
        """Bounding box in event output must be [x, y, w, h] (non-negative dimensions)."""
        frame = np.zeros((480, 640, 3), dtype=np.uint8) + 30
        cv2.rectangle(frame, (150, 150), (190, 180), (255, 255, 255), -1)
        mock_tracks = [
            {"keypoints": [{"name": "right_wrist", "x": 160.0, "y": 160.0, "confidence": 0.85}]}
        ]

        events = detector.process_frame(frame, frame_number=1, tracks=mock_tracks)
        assert len(events) >= 1
        bbox = events[0]["bounding_box"]
        x, y, w, h = bbox
        assert w > 0, "Width must be positive"
        assert h > 0, "Height must be positive"
        assert x >= 0 and y >= 0

    def test_process_frame_no_student_id_or_seat_zone(self, detector):
        """Per Section 8 contract — payload must NOT include student_id or seat_zone."""
        frame = np.zeros((480, 640, 3), dtype=np.uint8) + 30
        cv2.rectangle(frame, (150, 150), (190, 180), (255, 255, 255), -1)
        mock_tracks = [
            {
                "student_id": "student_001",
                "keypoints": [{"name": "left_wrist", "x": 160.0, "y": 160.0, "confidence": 0.85}],
            }
        ]

        events = detector.process_frame(frame, frame_number=1, tracks=mock_tracks)
        assert len(events) >= 1
        for ev in events:
            assert "student_id" not in ev, "student_id must NOT be in payload"
            assert "seat_zone" not in ev, "seat_zone must NOT be in payload"

    def test_debounce_cooldown(self, detector):
        """Same detection region must not trigger repeated events within debounce window."""
        frame = np.zeros((480, 640, 3), dtype=np.uint8) + 30
        cv2.rectangle(frame, (200, 200), (240, 230), (255, 255, 255), -1)
        mock_tracks = [
            {"keypoints": [{"name": "right_wrist", "x": 210.0, "y": 210.0, "confidence": 0.85}]}
        ]

        # Frame 1: Should fire
        ev1 = detector.process_frame(frame, frame_number=1, tracks=mock_tracks)
        assert len(ev1) == 1

        # Frame 2: Within debounce window (5 frames) → Should NOT fire
        ev2 = detector.process_frame(frame, frame_number=2, tracks=mock_tracks)
        assert len(ev2) == 0

        # Frame 10: After debounce window (10 - 1 = 9 >= 5) → Should fire again
        ev10 = detector.process_frame(frame, frame_number=10, tracks=mock_tracks)
        assert len(ev10) == 1

    def test_draw_detections(self, detector):
        """Visual annotation must draw on the frame and preserve frame dimensions."""
        frame = np.zeros((480, 640, 3), dtype=np.uint8)
        mock_events = [
            {
                "event_type": "phone_detected",
                "confidence": 0.85,
                "risk_score": 92.5,
                "risk_category": "high",
                "bounding_box": [100.0, 100.0, 50.0, 100.0],
            },
            {
                "event_type": "chit_detected",
                "confidence": 0.60,
                "risk_score": 58.0,
                "risk_category": "low",
                "bounding_box": [300.0, 200.0, 30.0, 20.0],
            },
        ]

        annotated = detector.draw_detections(frame, mock_events)
        assert annotated is not None
        assert annotated.shape == frame.shape
        assert np.any(annotated > 0)
